### ISSUE TITLE
Fix the sound on the play stand

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/made-invaders#12]
From #9:

At Maker Faire, the sound was disabled because the VS1053B that we had wouldn't play in the background and needed continual polling. 

To replace it, I have some SOMO-II modules that will work as we need. There's no arduino library for these that I've found, but I've included the basic functions in a new [somo-ii-lib](https://git.defproc.co.uk/DefProc/somo-ii-lib) to allow using this.

**Comment by epsaul** [comment]
Added an Arduino Sketch defining a Library of commands for a Software Serial out.
Commands for setting the volume and starting the MP3 file labeled xxx in folder yy on the micro SD card's root directory on the SOMO II.
@amcewen If you get a chance to view good practice (poor indenting etc.) comments would be useful also @DefProc @cheapjack let me know what other functions we might want and I'll add to the Library.

[Sound_Library.txt](https://github.com/DoESLiverpool/made-invaders/files/314691/Sound_Library.txt)

**Comment by DefProc** [comment]
Looks right to me. 

I've just pushed a version of [somo-ii-lib](https://git.defproc.co.uk/DefProc/somo-ii-lib) with better documentation, you should be able to [install it as a library](https://www.arduino.cc/en/Guide/Libraries) in the Arduino IDE.

I'll submit it to the Arduino libraries, and it should appear within a day or so in the Arduino library manager.

**Comment by DefProc** [comment]
That was quick, library now available through the arduino libraries manager

**Comment by DefProc** [comment]
added the somo-ii-lib, and set the sound and countdown timings
