### ISSUE TITLE
Generate Bitmap Images for the LED screen

### ISSUE THREAD

**Issue by cheapjack** [DoESLiverpool/made-invaders#3]
9 x 9 px 24bit colour `.bmp` format

**Comment by DefProc** [comment]
There's some examples and the invaders logo in the [target_images](https://github.com/DoESLiverpool/made-invaders/tree/master/target_images) folder

**Comment by cheapjack** [comment]
Made a minecraft bmp, couldn't resist
https://raw.githubusercontent.com/DoESLiverpool/made-invaders/master/target_images/mcdirtblock.bmp

**Comment by DefProc** [comment]
Looks good, more!

**Comment by DefProc** [comment]
Instructions: 

 * open a raster image program (e.g. [The Gimp](http://www.gimp.org/) (or Paint, or Photoshop)
 * create a new image, sized 9×9 pixels, RGB colour
 * draw your image
 * save or export as a BMP (Windows Bitmap Image) in the [target_images](https://github.com/DoESLiverpool/made-invaders/tree/master/target_images) folder
   * make sure the filename is 8 characters or less (FAT 8.3 file naming)
 * …
 * profit!
