### ISSUE TITLE
Add a camera for player action shots

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/made-invaders#4]
A lá rollercoaster pictures that can be added to the returned tweets

**Comment by brett-lempereur** [comment]
Cool, what kind of signals are being emitted by the rest of the code for this -- I think you had something in there already to send a signal to a Node-RED patch in MFUKLC, I'll probably piggy-back on that (in fact, if you're using the same registration station, it might be worth making it part of the same patch that handled the tweeting).

**Comment by DefProc** [comment]
Currently there's nothing sent. The easiest would be to send a signal at 15 seconds from the master controller to the pi (comes in as serial) that's picked up by node red on the registration station. 

We'll actually be sending at via the RFM69, but it'll arrive at the pi via serial. 

Any preference on the actual signal? Currently, the score and player ID are only sent at the end of play. I could send a "ready" signal including the player ID at the start of play if that helps.

**Comment by brett-lempereur** [comment]
Hmm, it's not just a question of taking the photograph.  Thinking about it, the interface for that should be extended with a check-box asking whether they want the photograph to be taken (default on).

Ideally this should hook into the same component that tweets the score back if they enter a twitter handle -- there's no point bombarding them with two tweets!  If you'd like this component to handle it, then yes, something like:

- 15 seconds into game: take photograph signal
- End of game: player id (twitter handle?), score, consent

Would work.

**Comment by DefProc** [comment]
At end-of-game only the player ID and score are sent. Only the registration station knows the twitter handle, so you'll have to look that up in the database (if it exists — there's no check by the main controller). It's probably better to also store consent on the registration station's database too.

**Comment by brett-lempereur** [comment]
Cool, I'll pop in Thursday afternoon to take a crack at this!

**Comment by DefProc** [comment]
While the camera worked at maker faire uk 2016, it didn't seem that important to players, so we'll put it on the back burner
