### ISSUE TITLE
What's the sound method that we're going to use?

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/made-invaders#5]
I've talking with @cheapjack and @epsaul about sound, but we'll have to make a decision sharpish about what sound method we're going actually use, current options include: 

 * triggering the same sounds each game, using the MP3 decoder (as used last year)
 * using a pi (e.g. pi zero) and sending some serial commands across and a python program will decide on what sounds to play, such as:
   * using stored mp3s
   * procedurally generating music using psonic and SonicPi
   * using espeak to say things
   * some other method
 * just having no sound

I should point out that we're not intending to have event sounds from hitting any targets, on the basis that we get a good noise when the dart hits, and it's difficult to implement and we don't have much time!

**Comment by cheapjack** [comment]
I've had a wee try earlier at using [python-sonic](https://github.com/gkvoelkl/python-sonic) as a way of using python-osc to connect to sonic pi and trigger sounds but would have to be quite basic. If I can get a test working by end of week may be worth pursuing before we fall back to the mp3 decoder.  Would have to get sonic-pi to boot up by itself and then run python-sonic scripts alongside but im sure ive seen someone do that. Be cool if @epsaul girls can programme some invader sounds for it if we can get the python thing working

I cant physically make it to Maker Faire this year tho' :(

**Comment by DefProc** [comment]
We'll go with MP3 triggering using the [Adafruit VS1053](https://learn.adafruit.com/adafruit-vs1053-mp3-aac-ogg-midi-wav-play-and-record-codec-tutorial/library-reference) that was on MFUKLC stand. We can extend this at a later date if necessary

**Comment by cheapjack** [comment]
Ive got a new VS1053 I can bring in tomorrow, just need to solder the headers on and place it on a breadboard and then @epsaul & me (if I can fit it in this week) can play with it and add the new rendered `mp3` files from his awesome compositions. We can refer to the original [`sound` branch](https://github.com/DefProc/mfuklc/blob/sound/range/arduino/control_module/control_module.ino) and then just swap it out with the existing one
